apiVersion: 1

datasources:
  - name: Chargeback SQLite
    type: frser-sqlite-datasource
    uid: chargeback-sqlite
    access: proxy
    jsonData:
      path: /var/lib/grafana/data/demo/confluent-cloud.db

