{
 "title": "Confluent Cloud Chargeback",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chargeback Data Available until",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "confluent_cloud_custom_scrape_status{object_type=\"billing_chargeback\"}",
     "legendFormat": "Billing Chargeback Status"
    }
   ]
  },
  {
   "title": "Overall Cost Breakdown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (confluent_cloud_chargeback_details)",
     "legendFormat": "Total Cost"
    },
    {
     "expr": "sum by (cost_type) (confluent_cloud_chargeback_details{cost_type=~\"UsageCost\"})",
     "legendFormat": "Usage Cost"
    },
    {
     "expr": "sum by (cost_type) (confluent_cloud_chargeback_details{cost_type=~\"SharedCost\"})",
     "legendFormat": "Shared Cost"
    }
   ]
  },
  { "title": "Cost breakdown summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cost breakdown per Environment",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (env_id) (confluent_cloud_billing_details)",
     "legendFormat": "{{env_id}}"
    }
   ]
  },
  {
   "title": "Cost breakdown per Kafka Cluster",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (kafka_cluster_id) (confluent_cloud_billing_details)",
     "legendFormat": "{{kafka_cluster_id}}"
    }
   ]
  },
  {
   "title": "Cost breakdown per Product Group",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (product_name) (confluent_cloud_billing_details)",
     "legendFormat": "{{product_name}}"
    }
   ]
  },
  {
   "title": "Cost breakdown per Product Line",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (product_line_type) (confluent_cloud_billing_details)",
     "legendFormat": "{{product_line_type}}"
    }
   ]
  },
  {
   "title": "Cost breakdown by Principal",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum (confluent_cloud_chargeback_details)",
     "legendFormat": "Total Chargeback"
    },
    {
     "expr": "sum by (principal) (confluent_cloud_chargeback_details)",
     "legendFormat": "{{principal}}"
    }
   ]
  },
  {
   "title": "Cost breakdown per Environment (Details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Split per Environment via Billing API",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (confluent_cloud_billing_details)",
       "legendFormat": "Total Cost"
      },
      {
       "expr": "sum by (env_id) (confluent_cloud_billing_details)",
       "legendFormat": "{{env_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost breakdown Per Kafka Cluster (Details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Split per Kafka Cluster via Billing API",
     "type": "stat",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (confluent_cloud_billing_details)",
       "legendFormat": "Total Cost"
      },
      {
       "expr": "sum by (kafka_cluster_id) (confluent_cloud_billing_details)",
       "legendFormat": "{{kafka_cluster_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost breakdown Per Resource (Details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Split per Resource via Billing API",
     "type": "stat",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (confluent_cloud_billing_details)",
       "legendFormat": "Total Cost"
      },
      {
       "expr": "sum by (resource_id) (confluent_cloud_billing_details)",
       "legendFormat": "{{resource_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cost Split per Product Line (Details)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cost Split per Product Line via Billing API",
     "type": "stat",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum (confluent_cloud_billing_details)",
       "legendFormat": "Total Cost"
      },
      {
       "expr": "sum by (product_line_type) (confluent_cloud_billing_details)",
       "legendFormat": "{{product_line_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CCloud Object Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Keys Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 1, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      { "expr": "count(confluent_cloud_api_key)" }
     ]
    },
    {
     "title": "Service Accounts Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      { "expr": "count(confluent_cloud_sa)" }
     ]
    },
    {
     "title": "User Accounts Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 7, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      { "expr": "count(confluent_cloud_user)" }
     ]
    },
    {
     "title": "Kafka Cluster Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 10, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "expr": "count (confluent_cloud_kafka_cluster)"
      }
     ]
    },
    {
     "title": "Environment Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 13, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "expr": "count (confluent_cloud_environment)"
      }
     ]
    },
    {
     "title": "Connector Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 16, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "expr": "count (confluent_cloud_connector)"
      }
     ]
    },
    {
     "title": "ksqlDB Cluster Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 19, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
     "targets": [
      {
       "expr": "count (confluent_cloud_ksqldb_cluster)"
      }
     ]
    }
   ]
  }
 ]
}